FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
MAINTAINER vsochat@stanford.edu
# docker build -f Dockerfile.py2 -t vanessa/pytorch-dev:py2.7 .
# docker push vanessa/pytorch-dev:py2.7
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         libjpeg-dev \
         libpng-dev &&\
     rm -rf /var/lib/apt/lists/*
ENV PYTHON_VERSION=2.7
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda config --add channels conda-forge && \
     /opt/conda/bin/conda install -y numpy pyyaml scipy ipython mkl && \
     /opt/conda/bin/conda install -y matplotlib scikit-learn scikit-image && \
     /opt/conda/bin/conda install -c intel mkl-include && \
     /opt/conda/bin/conda install -c pytorch magma-cuda90 && \
     /opt/conda/bin/conda clean -ya
RUN /opt/conda/bin/conda update -y conda
ENV PATH /opt/conda/bin:$PATH
# This must be done before pip so that requirements.txt is available
RUN git clone https://github.com/pytorch/pytorch /opt/pytorch && \   
    cd /opt/pytorch && \
    git submodule update --init
RUN pip install --upgrade pip
RUN TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .
RUN git clone https://github.com/pytorch/vision.git && cd vision && pip install -v .
WORKDIR /workspace
RUN chmod -R a+w /workspace
